### PR TITLE
Adds a few more checks to #send_event

### PR DESCRIPTION
**Pull request by curtis-rainforestqa**
Basically, do not try to send_event if some crucial pieces of
information are missing.

### CODE REVIEW

**Comment by epaulet** [comment]
We should probably log information for later debugging when something doesn't pass the checks. otherwise LGTM

**Comment by curtis-rainforestqa** [comment]
Great idea.

**Comment by epaulet** [comment]
LGTM. Does this also fix #88 ?

**Comment by curtis-rainforestqa** [comment]
I'm not sure if it completely addresses #88 but it is a step in the right direction. There's probably more logging we could do.

**Comment by epaulet** [comment]
k. we can log more types of errors and whatnot later on. :+1:

**Comment by curtis-rainforestqa** [comment]
Sounds good, thnx!

**Pull request merged**
