### PR TITLE
Return payload information by getting events

### PR DESCRIPTION
**Pull request by epaulet**
Not part of original project but this is a useful development reference for how the JSON is supposed to look.

### CODE REVIEW

**Comment by epaulet** [comment]
@jipiboily

**Comment by jipiboily** [comment]
@epaulet not sure what this is for...? Specs would help understand :grinning:

**Comment by ukd1** [comment]
@epaulet what is this? Why no specs?

**Comment by epaulet** [comment]
This is included in the new PR. https://github.com/rainforestapp/rainforest-integrations/pull/33

No specs because it's for dev use only. Gonna close this one because it's in the other PR already.

**Pull request closed without merging**
