### PR TITLE
Fix string interpolation in run description

### LINKED ISSUE #36: The description of test runs in HipChat have (run["description"]) as the name
Should be fixed in the current integration gem rather than waiting for the release of integrations v9000

### PR DESCRIPTION
**Pull request by epaulet**
Fixes this issue:

Fixes #36 
@rainforestapp/customer-product please review

### CODE REVIEW

**Comment by epaulet** [comment]
FYI I'm merging to master because integrations v9000 is on develop at the moment.

**Comment by juliankrispel** [comment]
@epaulet can you reopen this to merge into develop? Also why would integrations v9000 be on dev? It's far from complete?

**Comment by juliankrispel** [comment]
otherwise this looks good to me

**Comment by juliankrispel** [comment]
Oh I see this is rainforest-integrations, hmmm... ok

**Pull request merged**
