### PR TITLE
Message formatter refactor

### PR DESCRIPTION
**Pull request by dgolman**
Referencing Issue #61 

Needs to be tested by @epaulet.

### CODE REVIEW

**Comment by epaulet** [comment]
Methods like `run_href` can be folded into other methods now. They were only separated before because we needed to allow subclasses to overwrite parts of messages.

**Comment by dgolman** [comment]
Will fix that now. Pushing code once it is fixed.

**Comment by epaulet** [comment]
The changes are difficult to discern because the changes from the other branch are also here. Can you update the diff please?

**Comment by dgolman** [comment]
Yes, sorry for the confusion. Should of thought before pushing on which
branch I was branching off of. Will update you when pushed.

**Pull request closed without merging**
